---
provisioner:
  # no chef-client
  name: dummy

platforms:
  - name: docker
    transport:
      name: docker_cli
    driver:
      name: docker_cli
    driver_config:
      image: hexoide_configs:temp
      dockerfile: KitchenDockerfile
      # entrypoint: /bin/bash and command: /bin/bash do not work
      command:  -c 'while true; do sleep 1d; done;'

suites:
  - name: configs
    driver_config:
      container_name: kt-hexoide-conf
      volume:
        - <%= File.dirname(__FILE__) %>/test/integration/dummy_work:/ide/work
        - <%= File.dirname(__FILE__) %>/test/integration/identities/full:/ide/identity
        - <%= File.dirname(__FILE__) %>/test/integration/configs/bats:/tmp/bats
  - name: configs-no-ssh
    driver_config:
      container_name: kt-hexoide-conf_no_ssh
      volume:
        - <%= File.dirname(__FILE__) %>/test/integration/dummy_work:/ide/work
        - <%= File.dirname(__FILE__) %>/test/integration/identities/no_id_rsa:/ide/identity
        - <%= File.dirname(__FILE__) %>/test/integration/configs-no-ssh/bats:/tmp/bats
