---
provisioner:
  # no chef-client
  name: dummy

platforms:
  - name: docker-image
    transport:
      name: docker_cli
    driver:
      name: docker_cli
    driver_config:
      dockerfile: KitchenDockerfile
      # entrypoint: /bin/bash and command: /bin/bash do not work
      command:  -c 'while true; do sleep 1d; done;'
      image: <%= ENV['AIT_DOCKER_IMAGE_NAME'] %>:<%= ENV['AIT_DOCKER_IMAGE_TAG'] %>

suites:
  - name: default
    driver_config:
      container_name: kt-hexoide-image
      volume:
        - <%= File.dirname(__FILE__) %>/test/integration/dummy_work:/ide/work
        - <%= File.dirname(__FILE__) %>/test/integration/identities/full:/ide/identity
        - <%= File.dirname(__FILE__) %>/test/integration/default/bats:/tmp/bats
